server:
  port: 8083
grpc:
  port: ${GRPC_PORT:9094}
spring:
  application:
    name: body-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.agent: INFO
