// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/v1/sensor.proto

// Protobuf Java Version: 3.25.3
package com.agent.sensor.v1;

public interface ChannelHealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.v1.ChannelHealthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string channel_id = 1;</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>string channel_id = 1;</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();
}
