// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/v1/sensor.proto

// Protobuf Java Version: 3.25.3
package com.agent.sensor.v1;

public interface CollectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.v1.CollectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string batch_id = 1;</code>
   * @return The batchId.
   */
  java.lang.String getBatchId();
  /**
   * <code>string batch_id = 1;</code>
   * @return The bytes for batchId.
   */
  com.google.protobuf.ByteString
      getBatchIdBytes();

  /**
   * <code>string source_channel = 2;</code>
   * @return The sourceChannel.
   */
  java.lang.String getSourceChannel();
  /**
   * <code>string source_channel = 2;</code>
   * @return The bytes for sourceChannel.
   */
  com.google.protobuf.ByteString
      getSourceChannelBytes();

  /**
   * <code>int64 collect_time_ms = 3;</code>
   * @return The collectTimeMs.
   */
  long getCollectTimeMs();

  /**
   * <code>int32 item_count = 4;</code>
   * @return The itemCount.
   */
  int getItemCount();

  /**
   * <pre>
   * 六维质量综合分
   * </pre>
   *
   * <code>double quality_score = 5;</code>
   * @return The qualityScore.
   */
  double getQualityScore();

  /**
   * <pre>
   * 是否通过质检
   * </pre>
   *
   * <code>bool accepted = 6;</code>
   * @return The accepted.
   */
  boolean getAccepted();
}
