// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/v1/sensor.proto

// Protobuf Java Version: 3.25.3
package com.agent.sensor.v1;

/**
 * Protobuf type {@code sensor.v1.CollectResponse}
 */
public final class CollectResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensor.v1.CollectResponse)
    CollectResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CollectResponse.newBuilder() to construct.
  private CollectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CollectResponse() {
    batchId_ = "";
    sourceChannel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CollectResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.agent.sensor.v1.Sensor.internal_static_sensor_v1_CollectResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.agent.sensor.v1.Sensor.internal_static_sensor_v1_CollectResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.agent.sensor.v1.CollectResponse.class, com.agent.sensor.v1.CollectResponse.Builder.class);
  }

  public static final int BATCH_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object batchId_ = "";
  /**
   * <code>string batch_id = 1;</code>
   * @return The batchId.
   */
  @java.lang.Override
  public java.lang.String getBatchId() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchId_ = s;
      return s;
    }
  }
  /**
   * <code>string batch_id = 1;</code>
   * @return The bytes for batchId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBatchIdBytes() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_CHANNEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceChannel_ = "";
  /**
   * <code>string source_channel = 2;</code>
   * @return The sourceChannel.
   */
  @java.lang.Override
  public java.lang.String getSourceChannel() {
    java.lang.Object ref = sourceChannel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceChannel_ = s;
      return s;
    }
  }
  /**
   * <code>string source_channel = 2;</code>
   * @return The bytes for sourceChannel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceChannelBytes() {
    java.lang.Object ref = sourceChannel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceChannel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECT_TIME_MS_FIELD_NUMBER = 3;
  private long collectTimeMs_ = 0L;
  /**
   * <code>int64 collect_time_ms = 3;</code>
   * @return The collectTimeMs.
   */
  @java.lang.Override
  public long getCollectTimeMs() {
    return collectTimeMs_;
  }

  public static final int ITEM_COUNT_FIELD_NUMBER = 4;
  private int itemCount_ = 0;
  /**
   * <code>int32 item_count = 4;</code>
   * @return The itemCount.
   */
  @java.lang.Override
  public int getItemCount() {
    return itemCount_;
  }

  public static final int QUALITY_SCORE_FIELD_NUMBER = 5;
  private double qualityScore_ = 0D;
  /**
   * <pre>
   * 六维质量综合分
   * </pre>
   *
   * <code>double quality_score = 5;</code>
   * @return The qualityScore.
   */
  @java.lang.Override
  public double getQualityScore() {
    return qualityScore_;
  }

  public static final int ACCEPTED_FIELD_NUMBER = 6;
  private boolean accepted_ = false;
  /**
   * <pre>
   * 是否通过质检
   * </pre>
   *
   * <code>bool accepted = 6;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batchId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceChannel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceChannel_);
    }
    if (collectTimeMs_ != 0L) {
      output.writeInt64(3, collectTimeMs_);
    }
    if (itemCount_ != 0) {
      output.writeInt32(4, itemCount_);
    }
    if (java.lang.Double.doubleToRawLongBits(qualityScore_) != 0) {
      output.writeDouble(5, qualityScore_);
    }
    if (accepted_ != false) {
      output.writeBool(6, accepted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batchId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceChannel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceChannel_);
    }
    if (collectTimeMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, collectTimeMs_);
    }
    if (itemCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, itemCount_);
    }
    if (java.lang.Double.doubleToRawLongBits(qualityScore_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, qualityScore_);
    }
    if (accepted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, accepted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.agent.sensor.v1.CollectResponse)) {
      return super.equals(obj);
    }
    com.agent.sensor.v1.CollectResponse other = (com.agent.sensor.v1.CollectResponse) obj;

    if (!getBatchId()
        .equals(other.getBatchId())) return false;
    if (!getSourceChannel()
        .equals(other.getSourceChannel())) return false;
    if (getCollectTimeMs()
        != other.getCollectTimeMs()) return false;
    if (getItemCount()
        != other.getItemCount()) return false;
    if (java.lang.Double.doubleToLongBits(getQualityScore())
        != java.lang.Double.doubleToLongBits(
            other.getQualityScore())) return false;
    if (getAccepted()
        != other.getAccepted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId().hashCode();
    hash = (37 * hash) + SOURCE_CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + getSourceChannel().hashCode();
    hash = (37 * hash) + COLLECT_TIME_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCollectTimeMs());
    hash = (37 * hash) + ITEM_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getItemCount();
    hash = (37 * hash) + QUALITY_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQualityScore()));
    hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAccepted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.agent.sensor.v1.CollectResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.agent.sensor.v1.CollectResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.agent.sensor.v1.CollectResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.sensor.v1.CollectResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.agent.sensor.v1.CollectResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sensor.v1.CollectResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensor.v1.CollectResponse)
      com.agent.sensor.v1.CollectResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.agent.sensor.v1.Sensor.internal_static_sensor_v1_CollectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.agent.sensor.v1.Sensor.internal_static_sensor_v1_CollectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.agent.sensor.v1.CollectResponse.class, com.agent.sensor.v1.CollectResponse.Builder.class);
    }

    // Construct using com.agent.sensor.v1.CollectResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      batchId_ = "";
      sourceChannel_ = "";
      collectTimeMs_ = 0L;
      itemCount_ = 0;
      qualityScore_ = 0D;
      accepted_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.agent.sensor.v1.Sensor.internal_static_sensor_v1_CollectResponse_descriptor;
    }

    @java.lang.Override
    public com.agent.sensor.v1.CollectResponse getDefaultInstanceForType() {
      return com.agent.sensor.v1.CollectResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.agent.sensor.v1.CollectResponse build() {
      com.agent.sensor.v1.CollectResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.agent.sensor.v1.CollectResponse buildPartial() {
      com.agent.sensor.v1.CollectResponse result = new com.agent.sensor.v1.CollectResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.agent.sensor.v1.CollectResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.batchId_ = batchId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceChannel_ = sourceChannel_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.collectTimeMs_ = collectTimeMs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.itemCount_ = itemCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.qualityScore_ = qualityScore_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.accepted_ = accepted_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.agent.sensor.v1.CollectResponse) {
        return mergeFrom((com.agent.sensor.v1.CollectResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.agent.sensor.v1.CollectResponse other) {
      if (other == com.agent.sensor.v1.CollectResponse.getDefaultInstance()) return this;
      if (!other.getBatchId().isEmpty()) {
        batchId_ = other.batchId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSourceChannel().isEmpty()) {
        sourceChannel_ = other.sourceChannel_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCollectTimeMs() != 0L) {
        setCollectTimeMs(other.getCollectTimeMs());
      }
      if (other.getItemCount() != 0) {
        setItemCount(other.getItemCount());
      }
      if (other.getQualityScore() != 0D) {
        setQualityScore(other.getQualityScore());
      }
      if (other.getAccepted() != false) {
        setAccepted(other.getAccepted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              batchId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sourceChannel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              collectTimeMs_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              itemCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 41: {
              qualityScore_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              accepted_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object batchId_ = "";
    /**
     * <code>string batch_id = 1;</code>
     * @return The batchId.
     */
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string batch_id = 1;</code>
     * @return The bytes for batchId.
     */
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string batch_id = 1;</code>
     * @param value The batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string batch_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchId() {
      batchId_ = getDefaultInstance().getBatchId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string batch_id = 1;</code>
     * @param value The bytes for batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sourceChannel_ = "";
    /**
     * <code>string source_channel = 2;</code>
     * @return The sourceChannel.
     */
    public java.lang.String getSourceChannel() {
      java.lang.Object ref = sourceChannel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceChannel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string source_channel = 2;</code>
     * @return The bytes for sourceChannel.
     */
    public com.google.protobuf.ByteString
        getSourceChannelBytes() {
      java.lang.Object ref = sourceChannel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceChannel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string source_channel = 2;</code>
     * @param value The sourceChannel to set.
     * @return This builder for chaining.
     */
    public Builder setSourceChannel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceChannel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string source_channel = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceChannel() {
      sourceChannel_ = getDefaultInstance().getSourceChannel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string source_channel = 2;</code>
     * @param value The bytes for sourceChannel to set.
     * @return This builder for chaining.
     */
    public Builder setSourceChannelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceChannel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long collectTimeMs_ ;
    /**
     * <code>int64 collect_time_ms = 3;</code>
     * @return The collectTimeMs.
     */
    @java.lang.Override
    public long getCollectTimeMs() {
      return collectTimeMs_;
    }
    /**
     * <code>int64 collect_time_ms = 3;</code>
     * @param value The collectTimeMs to set.
     * @return This builder for chaining.
     */
    public Builder setCollectTimeMs(long value) {

      collectTimeMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 collect_time_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectTimeMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      collectTimeMs_ = 0L;
      onChanged();
      return this;
    }

    private int itemCount_ ;
    /**
     * <code>int32 item_count = 4;</code>
     * @return The itemCount.
     */
    @java.lang.Override
    public int getItemCount() {
      return itemCount_;
    }
    /**
     * <code>int32 item_count = 4;</code>
     * @param value The itemCount to set.
     * @return This builder for chaining.
     */
    public Builder setItemCount(int value) {

      itemCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 item_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      itemCount_ = 0;
      onChanged();
      return this;
    }

    private double qualityScore_ ;
    /**
     * <pre>
     * 六维质量综合分
     * </pre>
     *
     * <code>double quality_score = 5;</code>
     * @return The qualityScore.
     */
    @java.lang.Override
    public double getQualityScore() {
      return qualityScore_;
    }
    /**
     * <pre>
     * 六维质量综合分
     * </pre>
     *
     * <code>double quality_score = 5;</code>
     * @param value The qualityScore to set.
     * @return This builder for chaining.
     */
    public Builder setQualityScore(double value) {

      qualityScore_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 六维质量综合分
     * </pre>
     *
     * <code>double quality_score = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQualityScore() {
      bitField0_ = (bitField0_ & ~0x00000010);
      qualityScore_ = 0D;
      onChanged();
      return this;
    }

    private boolean accepted_ ;
    /**
     * <pre>
     * 是否通过质检
     * </pre>
     *
     * <code>bool accepted = 6;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return accepted_;
    }
    /**
     * <pre>
     * 是否通过质检
     * </pre>
     *
     * <code>bool accepted = 6;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {

      accepted_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否通过质检
     * </pre>
     *
     * <code>bool accepted = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      bitField0_ = (bitField0_ & ~0x00000020);
      accepted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensor.v1.CollectResponse)
  }

  // @@protoc_insertion_point(class_scope:sensor.v1.CollectResponse)
  private static final com.agent.sensor.v1.CollectResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.agent.sensor.v1.CollectResponse();
  }

  public static com.agent.sensor.v1.CollectResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CollectResponse>
      PARSER = new com.google.protobuf.AbstractParser<CollectResponse>() {
    @java.lang.Override
    public CollectResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CollectResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CollectResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.agent.sensor.v1.CollectResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

