// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor/v1/sensor.proto

// Protobuf Java Version: 3.25.3
package com.agent.sensor.v1;

public interface RegisterChannelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensor.v1.RegisterChannelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sensor.v1.ChannelType channel = 1;</code>
   * @return The enum numeric value on the wire for channel.
   */
  int getChannelValue();
  /**
   * <code>.sensor.v1.ChannelType channel = 1;</code>
   * @return The channel.
   */
  com.agent.sensor.v1.ChannelType getChannel();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string endpoint = 3;</code>
   * @return The endpoint.
   */
  java.lang.String getEndpoint();
  /**
   * <code>string endpoint = 3;</code>
   * @return The bytes for endpoint.
   */
  com.google.protobuf.ByteString
      getEndpointBytes();

  /**
   * <code>map&lt;string, string&gt; config = 4;</code>
   */
  int getConfigCount();
  /**
   * <code>map&lt;string, string&gt; config = 4;</code>
   */
  boolean containsConfig(
      java.lang.String key);
  /**
   * Use {@link #getConfigMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getConfig();
  /**
   * <code>map&lt;string, string&gt; config = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getConfigMap();
  /**
   * <code>map&lt;string, string&gt; config = 4;</code>
   */
  /* nullable */
java.lang.String getConfigOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; config = 4;</code>
   */
  java.lang.String getConfigOrThrow(
      java.lang.String key);

  /**
   * <code>string tenant_id = 5;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 5;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
