// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session/v1/session.proto

// Protobuf Java Version: 3.25.3
package com.agent.session.v1;

/**
 * Protobuf type {@code session.v1.AppendMessageResponse}
 */
public final class AppendMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:session.v1.AppendMessageResponse)
    AppendMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppendMessageResponse.newBuilder() to construct.
  private AppendMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppendMessageResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppendMessageResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.agent.session.v1.SessionOuterClass.internal_static_session_v1_AppendMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.agent.session.v1.SessionOuterClass.internal_static_session_v1_AppendMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.agent.session.v1.AppendMessageResponse.class, com.agent.session.v1.AppendMessageResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private com.agent.session.v1.Message message_;
  /**
   * <code>.session.v1.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.session.v1.Message message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public com.agent.session.v1.Message getMessage() {
    return message_ == null ? com.agent.session.v1.Message.getDefaultInstance() : message_;
  }
  /**
   * <code>.session.v1.Message message = 1;</code>
   */
  @java.lang.Override
  public com.agent.session.v1.MessageOrBuilder getMessageOrBuilder() {
    return message_ == null ? com.agent.session.v1.Message.getDefaultInstance() : message_;
  }

  public static final int MESSAGE_COUNT_FIELD_NUMBER = 2;
  private int messageCount_ = 0;
  /**
   * <pre>
   * 追加后消息总数
   * </pre>
   *
   * <code>int32 message_count = 2;</code>
   * @return The messageCount.
   */
  @java.lang.Override
  public int getMessageCount() {
    return messageCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMessage());
    }
    if (messageCount_ != 0) {
      output.writeInt32(2, messageCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessage());
    }
    if (messageCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, messageCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.agent.session.v1.AppendMessageResponse)) {
      return super.equals(obj);
    }
    com.agent.session.v1.AppendMessageResponse other = (com.agent.session.v1.AppendMessageResponse) obj;

    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (getMessageCount()
        != other.getMessageCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (37 * hash) + MESSAGE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getMessageCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.agent.session.v1.AppendMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.agent.session.v1.AppendMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.session.v1.AppendMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.agent.session.v1.AppendMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code session.v1.AppendMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:session.v1.AppendMessageResponse)
      com.agent.session.v1.AppendMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.agent.session.v1.SessionOuterClass.internal_static_session_v1_AppendMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.agent.session.v1.SessionOuterClass.internal_static_session_v1_AppendMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.agent.session.v1.AppendMessageResponse.class, com.agent.session.v1.AppendMessageResponse.Builder.class);
    }

    // Construct using com.agent.session.v1.AppendMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      messageCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.agent.session.v1.SessionOuterClass.internal_static_session_v1_AppendMessageResponse_descriptor;
    }

    @java.lang.Override
    public com.agent.session.v1.AppendMessageResponse getDefaultInstanceForType() {
      return com.agent.session.v1.AppendMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.agent.session.v1.AppendMessageResponse build() {
      com.agent.session.v1.AppendMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.agent.session.v1.AppendMessageResponse buildPartial() {
      com.agent.session.v1.AppendMessageResponse result = new com.agent.session.v1.AppendMessageResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.agent.session.v1.AppendMessageResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.messageCount_ = messageCount_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.agent.session.v1.AppendMessageResponse) {
        return mergeFrom((com.agent.session.v1.AppendMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.agent.session.v1.AppendMessageResponse other) {
      if (other == com.agent.session.v1.AppendMessageResponse.getDefaultInstance()) return this;
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (other.getMessageCount() != 0) {
        setMessageCount(other.getMessageCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              messageCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.agent.session.v1.Message message_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agent.session.v1.Message, com.agent.session.v1.Message.Builder, com.agent.session.v1.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.session.v1.Message message = 1;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     * @return The message.
     */
    public com.agent.session.v1.Message getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? com.agent.session.v1.Message.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public Builder setMessage(com.agent.session.v1.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public Builder setMessage(
        com.agent.session.v1.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public Builder mergeMessage(com.agent.session.v1.Message value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          message_ != null &&
          message_ != com.agent.session.v1.Message.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      if (message_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public com.agent.session.v1.Message.Builder getMessageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    public com.agent.session.v1.MessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            com.agent.session.v1.Message.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.session.v1.Message message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agent.session.v1.Message, com.agent.session.v1.Message.Builder, com.agent.session.v1.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.agent.session.v1.Message, com.agent.session.v1.Message.Builder, com.agent.session.v1.MessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private int messageCount_ ;
    /**
     * <pre>
     * 追加后消息总数
     * </pre>
     *
     * <code>int32 message_count = 2;</code>
     * @return The messageCount.
     */
    @java.lang.Override
    public int getMessageCount() {
      return messageCount_;
    }
    /**
     * <pre>
     * 追加后消息总数
     * </pre>
     *
     * <code>int32 message_count = 2;</code>
     * @param value The messageCount to set.
     * @return This builder for chaining.
     */
    public Builder setMessageCount(int value) {

      messageCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 追加后消息总数
     * </pre>
     *
     * <code>int32 message_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      messageCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:session.v1.AppendMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:session.v1.AppendMessageResponse)
  private static final com.agent.session.v1.AppendMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.agent.session.v1.AppendMessageResponse();
  }

  public static com.agent.session.v1.AppendMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppendMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<AppendMessageResponse>() {
    @java.lang.Override
    public AppendMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AppendMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppendMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.agent.session.v1.AppendMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

