// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session/v1/session.proto

// Protobuf Java Version: 3.25.3
package com.agent.session.v1;

public interface CitationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:session.v1.Citation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 来源类型（实时采集/知识库/模型生成）
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * 来源类型（实时采集/知识库/模型生成）
   * </pre>
   *
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <pre>
   * 引用 ID（doc/chunk/channel）
   * </pre>
   *
   * <code>string ref_id = 2;</code>
   * @return The refId.
   */
  java.lang.String getRefId();
  /**
   * <pre>
   * 引用 ID（doc/chunk/channel）
   * </pre>
   *
   * <code>string ref_id = 2;</code>
   * @return The bytes for refId.
   */
  com.google.protobuf.ByteString
      getRefIdBytes();

  /**
   * <pre>
   * 来源标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 来源标题
   * </pre>
   *
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 置信度 0-1
   * </pre>
   *
   * <code>double confidence = 4;</code>
   * @return The confidence.
   */
  double getConfidence();

  /**
   * <pre>
   * 采集时间 epoch ms
   * </pre>
   *
   * <code>int64 collected_at = 5;</code>
   * @return The collectedAt.
   */
  long getCollectedAt();
}
