// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session/v1/session.proto

// Protobuf Java Version: 3.25.3
package com.agent.session.v1;

public interface CreateSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:session.v1.CreateSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agent_id = 1;</code>
   * @return The agentId.
   */
  java.lang.String getAgentId();
  /**
   * <code>string agent_id = 1;</code>
   * @return The bytes for agentId.
   */
  com.google.protobuf.ByteString
      getAgentIdBytes();

  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
