// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/v1/health.proto

// Protobuf Java Version: 3.25.3
package com.agent.common.v1;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.v1.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.v1.HealthCheckResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.common.v1.HealthCheckResponse.Status status = 1;</code>
   * @return The status.
   */
  com.agent.common.v1.HealthCheckResponse.Status getStatus();

  /**
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>int64 uptime_seconds = 3;</code>
   * @return The uptimeSeconds.
   */
  long getUptimeSeconds();

  /**
   * <pre>
   * 依赖组件健康状态: redis=ok, qdrant=ok
   * </pre>
   *
   * <code>map&lt;string, string&gt; dependencies = 4;</code>
   */
  int getDependenciesCount();
  /**
   * <pre>
   * 依赖组件健康状态: redis=ok, qdrant=ok
   * </pre>
   *
   * <code>map&lt;string, string&gt; dependencies = 4;</code>
   */
  boolean containsDependencies(
      java.lang.String key);
  /**
   * Use {@link #getDependenciesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDependencies();
  /**
   * <pre>
   * 依赖组件健康状态: redis=ok, qdrant=ok
   * </pre>
   *
   * <code>map&lt;string, string&gt; dependencies = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDependenciesMap();
  /**
   * <pre>
   * 依赖组件健康状态: redis=ok, qdrant=ok
   * </pre>
   *
   * <code>map&lt;string, string&gt; dependencies = 4;</code>
   */
  /* nullable */
java.lang.String getDependenciesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 依赖组件健康状态: redis=ok, qdrant=ok
   * </pre>
   *
   * <code>map&lt;string, string&gt; dependencies = 4;</code>
   */
  java.lang.String getDependenciesOrThrow(
      java.lang.String key);
}
