// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brain/v1/brain.proto

// Protobuf Java Version: 3.25.3
package com.agent.brain.v1;

public interface RecognizeIntentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:brain.v1.RecognizeIntentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_query = 1;</code>
   * @return The userQuery.
   */
  java.lang.String getUserQuery();
  /**
   * <code>string user_query = 1;</code>
   * @return The bytes for userQuery.
   */
  com.google.protobuf.ByteString
      getUserQueryBytes();

  /**
   * <code>string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string tenant_id = 3;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 3;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @return A list containing the history.
   */
  java.util.List<java.lang.String>
      getHistoryList();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @return The count of history.
   */
  int getHistoryCount();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @param index The index of the element to return.
   * @return The history at the given index.
   */
  java.lang.String getHistory(int index);
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the history at the given index.
   */
  com.google.protobuf.ByteString
      getHistoryBytes(int index);
}
