// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brain/v1/brain.proto

// Protobuf Java Version: 3.25.3
package com.agent.brain.v1;

/**
 * Protobuf type {@code brain.v1.RecognizeIntentRequest}
 */
public final class RecognizeIntentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:brain.v1.RecognizeIntentRequest)
    RecognizeIntentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecognizeIntentRequest.newBuilder() to construct.
  private RecognizeIntentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecognizeIntentRequest() {
    userQuery_ = "";
    sessionId_ = "";
    tenantId_ = "";
    history_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecognizeIntentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.agent.brain.v1.Brain.internal_static_brain_v1_RecognizeIntentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.agent.brain.v1.Brain.internal_static_brain_v1_RecognizeIntentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.agent.brain.v1.RecognizeIntentRequest.class, com.agent.brain.v1.RecognizeIntentRequest.Builder.class);
  }

  public static final int USER_QUERY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userQuery_ = "";
  /**
   * <code>string user_query = 1;</code>
   * @return The userQuery.
   */
  @java.lang.Override
  public java.lang.String getUserQuery() {
    java.lang.Object ref = userQuery_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userQuery_ = s;
      return s;
    }
  }
  /**
   * <code>string user_query = 1;</code>
   * @return The bytes for userQuery.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserQueryBytes() {
    java.lang.Object ref = userQuery_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userQuery_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 3;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 3;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HISTORY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList history_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @return A list containing the history.
   */
  public com.google.protobuf.ProtocolStringList
      getHistoryList() {
    return history_;
  }
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @return The count of history.
   */
  public int getHistoryCount() {
    return history_.size();
  }
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @param index The index of the element to return.
   * @return The history at the given index.
   */
  public java.lang.String getHistory(int index) {
    return history_.get(index);
  }
  /**
   * <pre>
   * 对话历史
   * </pre>
   *
   * <code>repeated string history = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the history at the given index.
   */
  public com.google.protobuf.ByteString
      getHistoryBytes(int index) {
    return history_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userQuery_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userQuery_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tenantId_);
    }
    for (int i = 0; i < history_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, history_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userQuery_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userQuery_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tenantId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < history_.size(); i++) {
        dataSize += computeStringSizeNoTag(history_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getHistoryList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.agent.brain.v1.RecognizeIntentRequest)) {
      return super.equals(obj);
    }
    com.agent.brain.v1.RecognizeIntentRequest other = (com.agent.brain.v1.RecognizeIntentRequest) obj;

    if (!getUserQuery()
        .equals(other.getUserQuery())) return false;
    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getHistoryList()
        .equals(other.getHistoryList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getUserQuery().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (getHistoryCount() > 0) {
      hash = (37 * hash) + HISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.agent.brain.v1.RecognizeIntentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.agent.brain.v1.RecognizeIntentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agent.brain.v1.RecognizeIntentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.agent.brain.v1.RecognizeIntentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code brain.v1.RecognizeIntentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:brain.v1.RecognizeIntentRequest)
      com.agent.brain.v1.RecognizeIntentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.agent.brain.v1.Brain.internal_static_brain_v1_RecognizeIntentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.agent.brain.v1.Brain.internal_static_brain_v1_RecognizeIntentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.agent.brain.v1.RecognizeIntentRequest.class, com.agent.brain.v1.RecognizeIntentRequest.Builder.class);
    }

    // Construct using com.agent.brain.v1.RecognizeIntentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userQuery_ = "";
      sessionId_ = "";
      tenantId_ = "";
      history_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.agent.brain.v1.Brain.internal_static_brain_v1_RecognizeIntentRequest_descriptor;
    }

    @java.lang.Override
    public com.agent.brain.v1.RecognizeIntentRequest getDefaultInstanceForType() {
      return com.agent.brain.v1.RecognizeIntentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.agent.brain.v1.RecognizeIntentRequest build() {
      com.agent.brain.v1.RecognizeIntentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.agent.brain.v1.RecognizeIntentRequest buildPartial() {
      com.agent.brain.v1.RecognizeIntentRequest result = new com.agent.brain.v1.RecognizeIntentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.agent.brain.v1.RecognizeIntentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userQuery_ = userQuery_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        history_.makeImmutable();
        result.history_ = history_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.agent.brain.v1.RecognizeIntentRequest) {
        return mergeFrom((com.agent.brain.v1.RecognizeIntentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.agent.brain.v1.RecognizeIntentRequest other) {
      if (other == com.agent.brain.v1.RecognizeIntentRequest.getDefaultInstance()) return this;
      if (!other.getUserQuery().isEmpty()) {
        userQuery_ = other.userQuery_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.history_.isEmpty()) {
        if (history_.isEmpty()) {
          history_ = other.history_;
          bitField0_ |= 0x00000008;
        } else {
          ensureHistoryIsMutable();
          history_.addAll(other.history_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userQuery_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureHistoryIsMutable();
              history_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userQuery_ = "";
    /**
     * <code>string user_query = 1;</code>
     * @return The userQuery.
     */
    public java.lang.String getUserQuery() {
      java.lang.Object ref = userQuery_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userQuery_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_query = 1;</code>
     * @return The bytes for userQuery.
     */
    public com.google.protobuf.ByteString
        getUserQueryBytes() {
      java.lang.Object ref = userQuery_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userQuery_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_query = 1;</code>
     * @param value The userQuery to set.
     * @return This builder for chaining.
     */
    public Builder setUserQuery(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userQuery_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_query = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserQuery() {
      userQuery_ = getDefaultInstance().getUserQuery();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_query = 1;</code>
     * @param value The bytes for userQuery to set.
     * @return This builder for chaining.
     */
    public Builder setUserQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userQuery_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 2;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 2;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 2;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 3;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 3;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 3;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 3;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList history_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureHistoryIsMutable() {
      if (!history_.isModifiable()) {
        history_ = new com.google.protobuf.LazyStringArrayList(history_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @return A list containing the history.
     */
    public com.google.protobuf.ProtocolStringList
        getHistoryList() {
      history_.makeImmutable();
      return history_;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @return The count of history.
     */
    public int getHistoryCount() {
      return history_.size();
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param index The index of the element to return.
     * @return The history at the given index.
     */
    public java.lang.String getHistory(int index) {
      return history_.get(index);
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the history at the given index.
     */
    public com.google.protobuf.ByteString
        getHistoryBytes(int index) {
      return history_.getByteString(index);
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param index The index to set the value at.
     * @param value The history to set.
     * @return This builder for chaining.
     */
    public Builder setHistory(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHistoryIsMutable();
      history_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param value The history to add.
     * @return This builder for chaining.
     */
    public Builder addHistory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHistoryIsMutable();
      history_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param values The history to add.
     * @return This builder for chaining.
     */
    public Builder addAllHistory(
        java.lang.Iterable<java.lang.String> values) {
      ensureHistoryIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, history_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHistory() {
      history_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对话历史
     * </pre>
     *
     * <code>repeated string history = 4;</code>
     * @param value The bytes of the history to add.
     * @return This builder for chaining.
     */
    public Builder addHistoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureHistoryIsMutable();
      history_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:brain.v1.RecognizeIntentRequest)
  }

  // @@protoc_insertion_point(class_scope:brain.v1.RecognizeIntentRequest)
  private static final com.agent.brain.v1.RecognizeIntentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.agent.brain.v1.RecognizeIntentRequest();
  }

  public static com.agent.brain.v1.RecognizeIntentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecognizeIntentRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecognizeIntentRequest>() {
    @java.lang.Override
    public RecognizeIntentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecognizeIntentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecognizeIntentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.agent.brain.v1.RecognizeIntentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

