// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brain/v1/brain.proto

// Protobuf Java Version: 3.25.3
package com.agent.brain.v1;

public interface TaskStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:brain.v1.TaskStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string step_id = 1;</code>
   * @return The stepId.
   */
  java.lang.String getStepId();
  /**
   * <code>string step_id = 1;</code>
   * @return The bytes for stepId.
   */
  com.google.protobuf.ByteString
      getStepIdBytes();

  /**
   * <pre>
   * retrieve/tool_call/generate/summarize
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * retrieve/tool_call/generate/summarize
   * </pre>
   *
   * <code>string action = 2;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>map&lt;string, string&gt; params = 3;</code>
   */
  int getParamsCount();
  /**
   * <code>map&lt;string, string&gt; params = 3;</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParams();
  /**
   * <code>map&lt;string, string&gt; params = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParamsMap();
  /**
   * <code>map&lt;string, string&gt; params = 3;</code>
   */
  /* nullable */
java.lang.String getParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; params = 3;</code>
   */
  java.lang.String getParamsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 依赖的前置步骤
   * </pre>
   *
   * <code>repeated string depends_on = 4;</code>
   * @return A list containing the dependsOn.
   */
  java.util.List<java.lang.String>
      getDependsOnList();
  /**
   * <pre>
   * 依赖的前置步骤
   * </pre>
   *
   * <code>repeated string depends_on = 4;</code>
   * @return The count of dependsOn.
   */
  int getDependsOnCount();
  /**
   * <pre>
   * 依赖的前置步骤
   * </pre>
   *
   * <code>repeated string depends_on = 4;</code>
   * @param index The index of the element to return.
   * @return The dependsOn at the given index.
   */
  java.lang.String getDependsOn(int index);
  /**
   * <pre>
   * 依赖的前置步骤
   * </pre>
   *
   * <code>repeated string depends_on = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the dependsOn at the given index.
   */
  com.google.protobuf.ByteString
      getDependsOnBytes(int index);
}
